spring:
  kafka:
    jaas:
      enabled: true
      login-module: org.apache.kafka.common.security.plain.PlainLoginModule
      control-flag: required
      options.username: ${vcap.services.kafka-auth-poller-credhub.credentials.broker-credentials.shared_kafka_confluent_accesskey}
      options.password: ${vcap.services.kafka-auth-poller-credhub.credentials.broker-credentials.shared_kafka_confluent_secretkey}
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: PLAIN
    producer:
      acks: all
      bootstrap-servers: ${vcap.services.kafka.credentials.brokers}
      retries: 5
      buffer-memory: 33554432
      batch-size: 16384
      properties:
        interceptor.classes: com.gopenske.cf.foundation.services.interceptors.kafka.ProducerMessageInterceptor
        cf.functional.headers: cf_customer_id,cf_asset_id,cf_provider_cd,cf_feed_type,cf_source_id
        linger.ms:  2
        flush-ms: 3000
        schema.registry.url: ${vcap.services.kafka.credentials.schema.registry.url}
        basic.auth.credentials.source: USER_INFO
        basic.auth.user.info: ${vcap.services.kafka-auth-poller-credhub.credentials.schema-credentials.shared_schema_registry_accesskey}:${vcap.services.kafka-auth-poller-credhub.credentials.schema-credentials.shared_schema_registry_secretkey}
        compression-type: snappy
    consumer:
      auto-offset-reset: latest
      bootstrap-servers: ${vcap.services.kafka.credentials.brokers}
      enable-auto-commit: false
      heartbeat-interval: 3000
      isolation-level: read_committed
      max-poll-records: 3
      properties:
        linger.ms: 1
        max.poll.interval.ms: 15000
        schema.registry.url: ${vcap.services.kafka.credentials.schema.registry.url}
        basic.auth.credentials.source: USER_INFO
        basic.auth.user.info: ${vcap.services.kafka-auth-poller-credhub.credentials.schema-credentials.shared_schema_registry_accesskey}:${vcap.services.kafka-auth-poller-credhub.credentials.schema-credentials.shared_schema_registry_secretkey}
