management:
 tags:
  cf_feed_type: telemetry
  cf_provider_cd: xrs
  app: xrs-telemetry-poller
  source: xrs-telemetry-poller

wavefront:
 application:
    name: xrs-poller
    service: xrs-telemetry-poller
